### ISSUE TITLE
Error with filetype.vim in Ubuntu

### ISSUE THREAD

**Issue by mhaig** [mhaig/vimfiles#5]
Built latest `vim` from git on **Ubuntu 16.04.2 LTS**.  Upon launch this error is printed:

```
--- Auto-Commands ---
Error detected while processing /home/mhaig/.vim/filetype.vim:
line   49:
E10: \ should be followed by /, ? or &
line   50:
E10: \ should be followed by /, ? or &
line   51:
E10: \ should be followed by /, ? or &
line   52:
E10: \ should be followed by /, ? or &
line   53:
E10: \ should be followed by /, ? or &
```

See if this is a universal Ubuntu problem or unique to this VM.  Update `notes.txt` with any changes.

**Comment by drmikehenry** [comment]
I've seen this problem before.  It's caused by trying to use the system-provided `vimrc` file in the way that used to be recommended by vimfiles documentation when compiling a custom version of Vim.  The recommendation used to say to do the following:

    sudo ln -s /usr/share/vim/vimrc /usr/local/share/vim/vimrc

This advice was changed in the 2018-08-10 update of vimfiles.  Removing the link should fix the problem:

    sudo rm  /usr/local/share/vim/vimrc

**Comment by mhaig** [comment]
That was it, thank you!
